// Reference list for the template editor's variable picker
// (features/documents/components/variable-picker.tsx) — every key here is
// actually resolvable today by resolveKnownFieldValue in
// generate-document.service.ts. This is a reference/copy panel only:
// documents are edited in Word, not in-browser, so there's nothing to
// "insert into" here — just {{key}} tags to copy while typing them in Word.
export const KNOWN_TEMPLATE_VARIABLES = [
  { key: "employee_name", label: "Employee / Applicant Name", group: "Recipient" },
  { key: "designation", label: "Designation / Job Title", group: "Recipient" },
  { key: "department", label: "Department", group: "Recipient" },
  { key: "email", label: "Email", group: "Recipient" },
  { key: "basic_salary", label: "Basic Salary", group: "Salary (employees only)" },
  { key: "gross_salary", label: "Gross Salary", group: "Salary (employees only)" },
  { key: "probation_end_date", label: "Probation End Date", group: "Milestone Dates (employees only)" },
  { key: "confirmation_date", label: "Confirmation Date", group: "Milestone Dates (employees only)" },
  { key: "increment_eligibility_date", label: "Increment Eligibility Date", group: "Milestone Dates (employees only)" },
  { key: "contract_renewal_date", label: "Contract Renewal Date", group: "Milestone Dates (contract employees only)" },
  { key: "employee_code", label: "Employee Code", group: "Employee" },
  { key: "phone", label: "Phone", group: "Employee" },
  { key: "manager_name", label: "Manager Name", group: "Employee" },
  { key: "employment_type", label: "Employment Type", group: "Employee" },
  { key: "employment_status", label: "Employment Status", group: "Employee" },
  { key: "department_name", label: "Department Name", group: "Employee" },
  { key: "employee_type_name", label: "Employee Type", group: "Employee" },
  { key: "joining_date", label: "Joining Date", group: "Employee" },
  { key: "applicant_phone", label: "Applicant Phone", group: "Applicant" },
  { key: "job_title", label: "Job Title", group: "Applicant" },
  { key: "applicant_status", label: "Applicant Status", group: "Applicant" },
  { key: "source", label: "Application Source", group: "Applicant" },
  { key: "applied_date", label: "Applied Date", group: "Applicant" },
  { key: "location", label: "Location", group: "Applicant" },
  { key: "experience_years", label: "Experience (Years)", group: "Applicant" },
  { key: "current_position", label: "Current Position", group: "Applicant" },
  { key: "skills", label: "Skills", group: "Applicant" },
  { key: "resume_url", label: "Resume URL", group: "Applicant" },
  { key: "linkedin_url", label: "LinkedIn URL", group: "Applicant" },
  { key: "github_url", label: "GitHub URL", group: "Applicant" },
  { key: "portfolio_url", label: "Portfolio URL", group: "Applicant" },
  { key: "company_name", label: "Company Name", group: "Company" },
  { key: "company_logo_url", label: "Company Logo URL", group: "Company" },
  { key: "current_date", label: "Current Date", group: "System" },
  { key: "current_time", label: "Current Time", group: "System" },
  { key: "generated_by", label: "Generated By", group: "System" },
] as const;
