"use client";

import Link from "next/link";
import { useTransition } from "react";
import { toast } from "sonner";
import { Download, Trash2, FileText, User, UserSquare } from "lucide-react";
import { Button } from "@/components/ui/button";
import { EmptyState } from "@/components/shared/empty-state";
import { DocumentStatusMenu } from "@/features/documents/components/document-status-menu";
import { deleteGeneratedDocumentAction } from "@/actions/documents";
import type { GeneratedDocumentRow } from "@/server/repositories/generated-document.repository";

function DeleteButton({ id }: { id: string }) {
  const [isPending, startTransition] = useTransition();

  return (
    <Button
      variant="ghost"
      size="icon-sm"
      disabled={isPending}
      className="text-muted-foreground hover:text-destructive"
      onClick={() => {
        if (!confirm("Delete this document?")) return;
        startTransition(async () => {
          const result = await deleteGeneratedDocumentAction(id);
          if (!result.success) toast.error(result.error);
        });
      }}
    >
      <Trash2 className="size-4" />
    </Button>
  );
}

export function DocumentHistoryTable({ documents }: { documents: GeneratedDocumentRow[] }) {
  if (documents.length === 0) {
    return (
      <EmptyState
        icon={FileText}
        title="No documents match these filters"
        description="Try widening your filters, or generate a new document."
      />
    );
  }

  return (
    <table className="w-full text-sm">
      <thead className="border-b bg-muted/40 text-left text-xs text-muted-foreground">
        <tr>
          <th className="px-4 py-3 font-medium">Document Name</th>
          <th className="px-4 py-3 font-medium">Recipient</th>
          <th className="px-4 py-3 font-medium">Template</th>
          <th className="px-4 py-3 font-medium">Generated On</th>
          <th className="px-4 py-3 font-medium">Generated By</th>
          <th className="px-4 py-3 font-medium">Status</th>
          <th className="px-4 py-3 font-medium">Actions</th>
        </tr>
      </thead>
      <tbody className="divide-y">
        {documents.map((doc) => (
          <tr key={doc._id} className="hover:bg-muted/30">
            <td className="px-4 py-3 font-medium">{doc.fileName}</td>
            <td className="px-4 py-3 text-foreground/80">
              {doc.employee ? (
                <Link href={`/employees/${doc.employee._id}`} className="inline-flex items-center gap-1.5 hover:underline">
                  <User className="size-3.5 text-muted-foreground" />
                  {doc.employee.name}
                </Link>
              ) : doc.applicant ? (
                <Link href={`/applicants/${doc.applicant._id}`} className="inline-flex items-center gap-1.5 hover:underline">
                  <UserSquare className="size-3.5 text-muted-foreground" />
                  {doc.applicant.name}
                </Link>
              ) : (
                "—"
              )}
            </td>
            <td className="px-4 py-3 text-foreground/80">{doc.template?.name ?? "—"}</td>
            <td className="px-4 py-3 text-foreground/80">
              {new Date(doc.createdAt).toLocaleString("en-US", {
                month: "short",
                day: "numeric",
                year: "numeric",
                hour: "numeric",
                minute: "2-digit",
              })}
            </td>
            <td className="px-4 py-3 text-foreground/80">{doc.generatedBy?.name ?? "—"}</td>
            <td className="px-4 py-3">
              <DocumentStatusMenu documentId={doc._id} status={doc.status} />
            </td>
            <td className="px-4 py-3">
              <div className="flex items-center gap-1">
                {(doc.pdfUrl || doc.fileUrl) && (
                  <Button
                    variant="ghost"
                    size="icon-sm"
                    nativeButton={false}
                    render={<a href={(doc.pdfStatus === "ready" && doc.pdfUrl) || doc.fileUrl || "#"} download />}
                  >
                    <Download className="size-4" />
                  </Button>
                )}
                <DeleteButton id={doc._id} />
              </div>
            </td>
          </tr>
        ))}
      </tbody>
    </table>
  );
}
