"use client";

import { useTransition } from "react";
import { toast } from "sonner";
import { Download, Trash2, FileText } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { EmptyState } from "@/components/shared/empty-state";
import { deleteGeneratedDocumentAction } from "@/actions/documents";
import type { GeneratedDocumentRow } from "@/server/repositories/generated-document.repository";

const STATUS_VARIANT: Record<string, "secondary" | "outline"> = {
  generated: "secondary",
  sent: "secondary",
  signed: "secondary",
};

function DeleteButton({ id }: { id: string }) {
  const [isPending, startTransition] = useTransition();

  return (
    <Button
      variant="ghost"
      size="icon-sm"
      disabled={isPending}
      className="text-muted-foreground hover:text-destructive"
      onClick={() => {
        if (!confirm("Delete this document?")) return;
        startTransition(async () => {
          const result = await deleteGeneratedDocumentAction(id);
          if (!result.success) toast.error(result.error);
        });
      }}
    >
      <Trash2 className="size-4" />
    </Button>
  );
}

export function RecentDocumentsTable({ documents }: { documents: GeneratedDocumentRow[] }) {
  if (documents.length === 0) {
    return (
      <EmptyState
        icon={FileText}
        title="No documents generated yet"
        description="Documents you generate will show up here."
      />
    );
  }

  return (
    <table className="w-full text-sm">
      <thead className="border-b bg-muted/40 text-left text-xs text-muted-foreground">
        <tr>
          <th className="px-4 py-3 font-medium">Document Name</th>
          <th className="px-4 py-3 font-medium">Employee</th>
          <th className="px-4 py-3 font-medium">Template</th>
          <th className="px-4 py-3 font-medium">Generated On</th>
          <th className="px-4 py-3 font-medium">Generated By</th>
          <th className="px-4 py-3 font-medium">Status</th>
          <th className="px-4 py-3 font-medium">Actions</th>
        </tr>
      </thead>
      <tbody className="divide-y">
        {documents.map((doc) => (
          <tr key={doc._id} className="hover:bg-muted/30">
            <td className="px-4 py-3 font-medium">{doc.fileName}</td>
            <td className="px-4 py-3 text-foreground/80">{doc.employee?.name ?? "—"}</td>
            <td className="px-4 py-3 text-foreground/80">{doc.template?.name ?? "—"}</td>
            <td className="px-4 py-3 text-foreground/80">
              {new Date(doc.createdAt).toLocaleString("en-US", {
                month: "short",
                day: "numeric",
                year: "numeric",
                hour: "numeric",
                minute: "2-digit",
              })}
            </td>
            <td className="px-4 py-3 text-foreground/80">{doc.generatedBy?.name ?? "—"}</td>
            <td className="px-4 py-3">
              <Badge variant={STATUS_VARIANT[doc.status] ?? "outline"} className="capitalize">
                {doc.status}
              </Badge>
            </td>
            <td className="px-4 py-3">
              <div className="flex items-center gap-1">
                {doc.fileUrl && (
                  <Button variant="ghost" size="icon-sm" nativeButton={false} render={<a href={doc.fileUrl} download />}>
                    <Download className="size-4" />
                  </Button>
                )}
                <DeleteButton id={doc._id} />
              </div>
            </td>
          </tr>
        ))}
      </tbody>
    </table>
  );
}
